[project]
name = "de-zoom-camp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=7.1.0",
    "pandas>=2.3.3",
    "pyarrow>=23.0.0",
]
